language: node_js
node_js:
  - "node"
script:
  - npm run frontend:build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: frontend/dist
  on:
    branch: master

  provider: heroku
  api_key:
    secure: "bc5aeb12-ab8a-4ccc-939e-e0340eff0be2"
  app: graduation-project-server
  
